In [1]:
from pymongo import MongoClient
import pandas as pd
from pandas.io.json import json_normalize

In [2]:
client = MongoClient("mongodb://localhost/companies")

In [3]:
db = client.get_database()

In [5]:
a = list(db["companies"].find())
a[:1]

[{'_id': ObjectId('52cdef7c4bab8bd675297d8b'),
  'acquisition': None,
  'acquisitions': [],
  'alias_list': 'Zoho ManageEngine ',
  'blog_feed_url': '',
  'blog_url': '',
  'category_code': 'enterprise',
  'competitions': [],
  'created_at': datetime.datetime(2007, 5, 25, 19, 24, 22),
  'crunchbase_url': 'http://www.crunchbase.com/company/adventnet',
  'deadpooled_year': 2,
  'description': 'Server Management Software',
  'email_address': 'pr@adventnet.com',
  'external_links': [],
  'founded_year': 1996,
  'funding_rounds': [],
  'homepage_url': 'http://adventnet.com',
  'image': {'available_sizes': [[[150, 55],
     'assets/images/resized/0001/9732/19732v1-max-150x150.png'],
    [[150, 55], 'assets/images/resized/0001/9732/19732v1-max-250x250.png'],
    [[150, 55], 'assets/images/resized/0001/9732/19732v1-max-450x450.png']]},
  'investments': [],
  'milestones': [],
  'name': 'AdventNet',
  'number_of_employees': 600,
  'offices': [{'address1': '4900 Hopyard Rd.',
    'address2': 'Suite 310',
    'city': 'Pleasanton',
    'country_code': 'USA',
    'description': 'Headquarters',
    'latitude': 37.692934,
    'longitude': -121.904945,
    'state_code': 'CA',
    'zip_code': '94588'}],
  'overview': '<p>AdventNet is now <a href="/company/zoho-manageengine" title="Zoho ManageEngine" rel="nofollow">Zoho ManageEngine</a>.</p>\n\n<p>Founded in 1996, AdventNet has served a diverse range of enterprise IT, networking and telecom customers.</p>\n\n<p>AdventNet supplies server and network management software.</p>',
  'partners': [],
  'permalink': 'abc3',
  'phone_number': '925-924-9500',
  'products': [],
  'providerships': [{'is_past': True,
    'provider': {'name': 'A Small Orange', 'permalink': 'a-small-orange'},
    'title': 'DHFH'}],
  'relationships': [{'is_past': True,
    'person': {'first_name': 'Sridhar',
     'last_name': 'Vembu',
     'permalink': 'sridhar-vembu'},
    'title': 'CEO and Co-Founder'},
   {'is_past': True,
    'person': {'first_name': 'Neil',
     'last_name': 'Butani',
     'permalink': 'neil-butani'},
    'title': 'VP of Business Dev'},
   {'is_past': True,
    'person': {'first_name': 'Bharath',
     'last_name': 'Balasubramanian',
     'permalink': 'bharath-balasibramanian'},
    'title': 'Usabiliy Engineer'},
   {'is_past': True,
    'person': {'first_name': 'Rajendran',
     'last_name': 'Dandapani',
     'permalink': 'rajendran-dandapani'},
    'title': 'Director of Engineering'},
   {'is_past': True,
    'person': {'first_name': 'Aravind',
     'last_name': 'Natarajan',
     'permalink': 'aravind-natarajan'},
    'title': 'Market Analyst'},
   {'is_past': True,
    'person': {'first_name': 'Hyther',
     'last_name': 'Nizam',
     'permalink': 'hyther-nizam'},
    'title': 'Director of Product Management'},
   {'is_past': True,
    'person': {'first_name': 'Ian',
     'last_name': 'Wenig',
     'permalink': 'ian-wenig'},
    'title': 'Western Regional OEM Sales Manager'}],
  'screenshots': [{'attribution': None,
    'available_sizes': [[[150, 94],
      'assets/images/resized/0004/3400/43400v1-max-150x150.png'],
     [[250, 156], 'assets/images/resized/0004/3400/43400v1-max-250x250.png'],
     [[450, 282],
      'assets/images/resized/0004/3400/43400v1-max-450x450.png']]}],
  'tag_list': '',
  'total_money_raised': '$0',
  'twitter_username': 'manageengine',
  'updated_at': 'Wed Oct 31 18:26:09 UTC 2012',
  'video_embeds': []}]

In [6]:
df = pd.DataFrame(a)

In [7]:
df = json_normalize(a)

In [8]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [9]:
col = ['offices']
df1 = df.loc[:,col]

In [10]:
df1.head()

                                             offices
0  [{'description': 'Headquarters', 'address1': '...
1  [{'description': '', 'address1': '710 - 2nd Av...
2  [{'description': '', 'address1': 'Suite 200', ...
3  [{'description': None, 'address1': '959 Skyway...
4  [{'description': 'Headquarters', 'address1': '...

In [11]:
m = df1.explode("offices")
q = m[["offices"]].apply(lambda r: r.offices ,result_type="expand", axis=1)

In [12]:
df2 = pd.concat([m,q],axis=1)
df2.head()

,offices,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,"{'description': 'Headquarters', 'address1': '4...",Headquarters,4900 Hopyard Rd.,Suite 310,94588,Pleasanton,CA,USA,37.692934,-121.904945
1,"{'description': '', 'address1': '710 - 2nd Ave...",,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253
1,"{'description': '', 'address1': '270 Lafayette...",,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431
2,"{'description': '', 'address1': 'Suite 200', '...",,Suite 200,654 High Street,94301,Palo Alto,CA,ISR,NaN,NaN
3,"{'description': None, 'address1': '959 Skyway ...",None,"959 Skyway Road, Suite 200",None,94070,San Carlos,CA,USA,37.506885,-122.247573

In [13]:
df2['country_code'].value_counts()

USA    10229
GBR     1385
CAN      621
IND      519
DEU      407
FRA      375
AUS      272
ESP      240
ISR      239
CHN      209
NLD      194
JPN      148
IRL      136
SWE      131
ITA      111
CHE      104
SGP       85
BEL       84
ARG       66
BRA       55
RUS       55
DNK       54
NZL       53
FIN       52
HKG       46
PRT       44
NOR       41
TUR       40
ZAF       40
AUT       38
TWN       35
ROM       33
POL       32
KOR       31
UKR       29
ARE       27
MEX       27
CZE       25
MYS       24
PHL       22
PAK       22
GRC       20
THA       17
EST       15
EGY       13
SVN       12
LVA       11
BGR       10
CHL       10
HUN       10
VNM       10
IDN       10
CYP        9
COL        8
ISL        8
URY        8
LUX        7
HRV        7
LTU        7
JOR        6
ANT        6
SAU        6
MLT        6
CRI        5
BGD        5
BRB        4
MUS        4
KEN        4
MAR        4
LKA        4
NGA        4
QAT        4
CSS        4
AFG        3
MKD        3
BLR        3
VGB        3
LBN        2
PRI        2
DOM        2
GIB        2
UZB        2
NIC        2
TUN        2
SDN        2
CIV        2
LIE        2
VEN        2
ARA        2
PAN        2
BIH        2
BMU        2
PER        2
KAZ        2
PRK        2
UMI        1
CYM        1
PST        1
ARM        1
MTQ        1
REU        1
GIN        1
BFA        1
KGZ        1
OMN        1
IRQ        1
ECU        1
IOT        1
AZE        1
GHA        1
LAO        1
ALB        1
ATG        1
BOL        1
Name: country_code, dtype: int64

In [14]:
a = df2['country_code'] == 'ESP'

In [15]:
b = df2[a]
b['city'].value_counts()

Madrid                    85
Barcelona                 63
                           8
Valencia                   5
Zaragoza                   4
Malaga                     3
Marbella                   3
A CoruÃ±a                  2
Palma de Mallorca          2
MatarÃ³ (Barcelona)        2
Pozuelo de Alarcon         2
Santiago de Compostela     2
Paterna, Valencia          2
Las Rozas                  2
Alicante                   2
Barakaldo                  2
Bilbao                     2
Gijon                      1
Tres Cantos, Madrid        1
Las rozas, Madrid          1
CÃ³rdoba                   1
SalobreÃ±a, Granada        1
Sabadell                   1
LeÃ³n                      1
Sant Cugat del VallÃ¨s     1
Bellaterra                 1
Alcoy                      1
Las Rozaas                 1
AlcorcÃ³n (Madrid)         1
Teruel                     1
Alcobendas                 1
LogroÃ±o                   1
Terrassa                   1
Villamayor                 1
les Fonts - Barcelona      1
San Sebastián              1
Las Rozas (Madrid)         1
Adeje                      1
madrid                     1
Cerdanyola                 1
Brunete                    1
Rubi (Barcelona)           1
Murcia                     1
Sevilla                    1
Torrelavega                1
Leon                       1
El Masnou                  1
zaragoza                   1
Arrecife                   1
KrakÃ³w                    1
AlcalÃ¡ de Henares         1
Gelida                     1
Lugones                    1
Vigo                       1
Toledo                     1
Infiesto (Asturias)        1
Figueres, Girona           1
Pamplona                   1
Sant Cugat del VallÃ©s     1
Seville                    1
Getafe                     1
CornellÃ  de Llobregat     1
Barcelona, 08019           1
Paterna (Valencia)         1
Alcala de Guadaira         1
VALLADOLID                 1
Name: city, dtype: int64

In [16]:
df.head()

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,deadpooled_year,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,products,relationships,competitions,providerships,total_money_raised,funding_rounds,investments,acquisition,acquisitions,offices,milestones,video_embeds,screenshots,external_links,partners,image.available_sizes,founded_month,founded_day,acquisition.price_amount,acquisition.price_currency_code,acquisition.term_code,acquisition.source_url,acquisition.source_description,acquisition.acquired_year,acquisition.acquired_month,acquisition.acquired_day,acquisition.acquiring_company.name,acquisition.acquiring_company.permalink,deadpooled_month,deadpooled_day,deadpooled_url,ipo,image.attribution,image,ipo.valuation_amount,ipo.valuation_currency_code,ipo.pub_year,ipo.pub_month,ipo.pub_day,ipo.stock_symbol
0,52cdef7c4bab8bd675297d8b,AdventNet,abc3,http://www.crunchbase.com/company/adventnet,http://adventnet.com,,,manageengine,enterprise,600.0,1996.0,2.0,,Zoho ManageEngine,pr@adventnet.com,925-924-9500,Server Management Software,2007-05-25 19:24:22,Wed Oct 31 18:26:09 UTC 2012,"<p>AdventNet is now <a href=""/company/zoho-man...",[],"[{'is_past': True, 'title': 'CEO and Co-Founde...",[],"[{'title': 'DHFH', 'is_past': True, 'provider'...",$0,[],[],NaN,[],"[{'description': 'Headquarters', 'address1': '...",[],[],"[{'available_sizes': [[[150, 94], 'assets/imag...",[],[],"[[[150, 55], assets/images/resized/0001/9732/1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,52cdef7c4bab8bd675297d8a,Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,2005.0,1.0,"wiki, seattle, elowitz, media-industry, media-...",,info@wetpaint.com,206.859.6300,Technology Platform Company,2007-05-25 06:51:27,Sun Dec 08 07:15:44 UTC 2013,<p>Wetpaint is a technology platform company t...,"[{'name': 'Wikison Wetpaint', 'permalink': 'we...","[{'is_past': False, 'title': 'Co-Founder and V...","[{'competitor': {'name': 'Wikia', 'permalink':...",[],$39.8M,"[{'id': 888, 'round_code': 'a', 'source_url': ...",[],NaN,[],"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],"[[[150, 75], assets/images/resized/0000/3604/3...",10.0,17.0,30000000.0,USD,cash_and_stock,http://allthingsd.com/20131216/viggle-tries-to...,Viggle Tries to Bulk Up Its Social TV Busines...,2013.0,12.0,16.0,Viggle,viggle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,52cdef7c4bab8bd675297d8f,Omnidrive,omnidrive,http://www.crunchbase.com/company/omnidrive,http://www.omnidrive.com,http://www.omnidrive.com/blog,http://feeds.feedburner.com/omnidrive,Nomadesk,network_hosting,NaN,2005.0,2008.0,"storage, sharing, edit, online",None,info@omnidrive.com,660-675-5052,None,Sun May 27 03:25:32 UTC 2007,Tue Jul 02 22:48:04 UTC 2013,"<p>Currently in public beta, Omnidrive makes i...","[{'name': 'Omnidrive', 'permalink': 'omnidrive'}]","[{'is_past': True, 'title': 'Co-founder', 'per...","[{'competitor': {'name': 'Dropbox', 'permalink...",[],$800k,"[{'id': 225, 'round_code': 'angel', 'source_ur...",[],NaN,[],"[{'description': '', 'address1': 'Suite 200', ...",[],[],[],[],[],"[[[150, 85], assets/images/resized/0000/0823/8...",11.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,15.0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,52cdef7c4bab8bd675297d90,Postini,postini,http://www.crunchbase.com/company/postini,http://postini.com,,,None,web,NaN,1999.0,NaN,,None,,888.584.3150,None,Fri Jun 08 12:19:51 UTC 2007,Sat Aug 13 18:02:34 UTC 2011,<p>Postini focuses on two main issues: securit...,"[{'name': 'Postini Solutions', 'permalink': 'p...","[{'is_past': False, 'title': 'Board', 'person'...","[{'competitor': {'name': 'RescueTime', 'permal...",[],$0,[],[],NaN,[],"[{'description': None, 'address1': '959 Skyway...",[],[],[],[],[],"[[[150, 61], assets/images/resized/0000/3697/3...",6.0,2.0,625000000.0,USD,cash,http://www.techcrunch.com/2007/07/09/google-ac...,http://www.techcrunch.com/2007/07/09/google-ac...,2007.0,7.0,9.0,Google,google,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,52cdef7c4bab8bd675297d8c,Zoho,abc4,http://www.crunchbase.com/company/zoho,http://zoho.com,http://blogs.zoho.com/,http://blogs.zoho.com/feed,zoho,software,1600.0,2005.0,3.0,"zoho, officesuite, spreadsheet, writer, projec...",,info@zohocorp.com,1-888-204-3539,Online Business Apps Suite,Fri May 25 19:30:28 UTC 2007,Wed Oct 30 00:07:05 UTC 2013,"<p>Zoho offers a suite of Business, Collaborat...","[{'name': 'Zoho Office Suite', 'permalink': 'z...","[{'is_past': False, 'title': 'CEO and Founder'...","[{'competitor': {'name': 'Empressr', 'permalin...",[],$0,[],[],NaN,[],"[{'description': 'Headquarters', 'address1': '...","[{'id': 388, 'description': 'Zoho Reaches 2 Mi...","[{'embed_code': '<object width=""430"" height=""2...",[],[{'external_url': 'http://www.online-tech-tips...,[],"[[[150, 55], assets/images/resized/0000/3946/3...",9.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

APARTE

Saco solamente columnas de interés para limpiar la localización

In [4]:
companies = list(db.companies.find({},{"name":1,"offices":1,"category_code":1}))

Convertimos en pandas para ver mejor los datos

In [5]:
df = pd.DataFrame(companies)
df.head()

,_id,name,category_code,offices
0,52cdef7c4bab8bd675297d8b,AdventNet,enterprise,"[{'description': 'Headquarters', 'address1': '..."
1,52cdef7c4bab8bd675297d8a,Wetpaint,web,"[{'description': '', 'address1': '710 - 2nd Av..."
2,52cdef7c4bab8bd675297d8f,Omnidrive,network_hosting,"[{'description': '', 'address1': 'Suite 200', ..."
3,52cdef7c4bab8bd675297d90,Postini,web,"[{'description': None, 'address1': '959 Skyway..."
4,52cdef7c4bab8bd675297d8c,Zoho,software,"[{'description': 'Headquarters', 'address1': '..."

Separamos los datos contenidos en la columna offices

In [6]:
df = df.explode("offices")
expand = df[["offices"]].apply(lambda r: r.offices ,result_type="expand", axis=1)
df2 = pd.concat([df,expand],axis=1)
df2.head()

,_id,name,category_code,offices,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,52cdef7c4bab8bd675297d8b,AdventNet,enterprise,"{'description': 'Headquarters', 'address1': '4...",Headquarters,4900 Hopyard Rd.,Suite 310,94588,Pleasanton,CA,USA,37.692934,-121.904945
1,52cdef7c4bab8bd675297d8a,Wetpaint,web,"{'description': '', 'address1': '710 - 2nd Ave...",,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253
1,52cdef7c4bab8bd675297d8a,Wetpaint,web,"{'description': '', 'address1': '270 Lafayette...",,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431
2,52cdef7c4bab8bd675297d8f,Omnidrive,network_hosting,"{'description': '', 'address1': 'Suite 200', '...",,Suite 200,654 High Street,94301,Palo Alto,CA,ISR,NaN,NaN
3,52cdef7c4bab8bd675297d90,Postini,web,"{'description': None, 'address1': '959 Skyway ...",None,"959 Skyway Road, Suite 200",None,94070,San Carlos,CA,USA,37.506885,-122.247573

Elimamos la columna offices

In [7]:
df2 = df2.drop(columns=["offices"])

In [9]:
df2.head()

,_id,name,category_code,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,52cdef7c4bab8bd675297d8b,AdventNet,enterprise,Headquarters,4900 Hopyard Rd.,Suite 310,94588,Pleasanton,CA,USA,37.692934,-121.904945
1,52cdef7c4bab8bd675297d8a,Wetpaint,web,,710 - 2nd Avenue,Suite 1100,98104,Seattle,WA,USA,47.603122,-122.333253
1,52cdef7c4bab8bd675297d8a,Wetpaint,web,,270 Lafayette Street,Suite 505,10012,New York,NY,USA,40.723731,-73.996431
2,52cdef7c4bab8bd675297d8f,Omnidrive,network_hosting,,Suite 200,654 High Street,94301,Palo Alto,CA,ISR,NaN,NaN
3,52cdef7c4bab8bd675297d90,Postini,web,None,"959 Skyway Road, Suite 200",None,94070,San Carlos,CA,USA,37.506885,-122.247573